# Generated by Django 3.0.7 on 2020-07-16 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=25)),
                ('temp', models.IntegerField(default=0)),
                ('date', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name_plural': 'temps',
            },
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
