# Generated by Django 3.0.7 on 2020-07-17 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0002_auto_20200716_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temp',
            name='date',
            field=models.DateField(),
        ),
    ]
